CREATE CACHED TABLE IF NOT EXISTS PUBLIC.REPO (
    ID INTEGER NOT NULL CHECK (ID >= 1),
    DESCRIPTION VARCHAR(1000),
    NAME VARCHAR(255) NOT NULL
);

-- example to add a new field: ALTER TABLE PUBLIC.REPO ADD COLUMN IF NOT EXISTS NEWFIELDNAME VARCHAR(255) DEFAULT '';

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.PULLREQUEST (
    ID INTEGER NOT NULL CHECK (ID >= 1),
    CREATEDAT VARCHAR(255),
    FILESCHANGED INTEGER,
    LINESADDED INTEGER,
    LINESREMOVED INTEGER,
    NUMBER INTEGER,
    STATE VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255),
    URL VARCHAR(255),
    ASSIGNEE_ID INTEGER,
    AUTHOR_ID INTEGER NOT NULL,
    REPO_ID INTEGER NOT NULL
);


CREATE CACHED TABLE IF NOT EXISTS PUBLIC.USER (
    ID INTEGER NOT NULL,
    AVATARURL VARCHAR(255),
    CANLOGIN BOOLEAN,
    USERNAME VARCHAR(255) NOT NULL
);